--- #signifies yml file

name: Checks

on: [push]

jobs:
  test-lint: # idea of job
    name: Test and Lint # name displayed in github ui
    runs-on: ubuntu-20.04 # runner is the OS where we run th job on, docker compose is already installed on this
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 #uses allows you to use another pre-made(existing) action that's provided to you in githubs action repo
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # this step is used to run test and linting on code
        uses: actions/checkout@v2 # Checks our code out, action is provided by github
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"